name: Edwardspace
favicon: null
layout_spectrum: 0.75622
typography_spectrum: 0.6909596277400851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090e11'
    - '#484e5e'
    - '#c99774'
    - '#e7c6a5'
  brandStrength: 0.9066306941676885
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
