name: Edwardspace
favicon: null
layout_spectrum: 0.73964
typography_spectrum: 0.49931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cee1d9'
    - '#b5ad92'
    - '#86826e'
    - '#282d29'
    - '#6f6757'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
