name: Edwardspace
favicon: null
layout_spectrum: 0.50207
typography_spectrum: 0.6909596277400851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f4f5'
    - '#bdb7c1'
    - '#95868d'
    - '#3a2f2b'
    - '#986635'
  brandStrength: 0.9066306941676885
  lightness: 0.79067058628425
  saturation: 0.06835330836474895
  rhythmicContrast: 0.07250934443436563
purpose: []
